services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: refmd
      POSTGRES_USER: refmd
      POSTGRES_PASSWORD: refmd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U refmd"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      FRONTEND_URL=http://localhost:3000
      DATABASE_URL: postgresql://refmd:refmd@postgres:5432/refmd
      PORT: 8888
      JWT_SECRET: your-secret-key-change-this-in-production
      JWT_EXPIRY: 604800
      REFRESH_TOKEN_EXPIRY: 604800
      BCRYPT_COST: 10
      UPLOAD_MAX_SIZE: 10485760
      UPLOAD_DIR: ./documents
      GIT_SYNC_ENABLED: true
      GIT_AUTO_SYNC: true
      GIT_SYNC_INTERVAL: 300
      RUST_LOG: info
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./documents:/app/documents

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_URL: http://localhost:8888/api
      SOCKET_URL: http://localhost:8888
      SITE_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_data: