# Default values for refmd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configuration
global:
  # Optional: Set a fixed external URL (overrides automatic URL detection)
  # externalUrl: https://refmd.example.com
  externalUrl: ""
  
  # Advanced URL configuration
  # When enabled, allows separate URLs for API and Socket connections
  # Useful when API and App run on different domains, ports, or behind different load balancers
  separateUrls:
    enabled: false
    apiUrl: "http://localhost:8888/api"     # API endpoint URL (e.g., https://api.refmd.com/api)
    socketUrl: "http://localhost:8888"  # WebSocket endpoint URL (e.g., wss://api.refmd.com)

replicaCount: 1

image:
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Service configuration
service:
  api:
    type: ClusterIP
    port: 8888
  app:
    type: ClusterIP
    port: 3000

# RefMD specific configuration
refmd:
  api:
    # IMPORTANT: Change this in production!
    jwtSecret: "dev-secret-key-change-in-production"
    jwtExpiry: 3600
    refreshTokenExpiry: 604800
    bcryptCost: 12
    uploadMaxSize: 10485760
    uploadDir: "/app/refmd"
    gitSyncEnabled: "true"
    gitAutoSync: "false"
    gitSyncInterval: 300
    signupEnabled: "true"
  
  app:
    signupEnabled: "true"

# API deployment configuration
api:
  image:
    repository: ghcr.io/munenick/refmd-api
    tag: latest
  
  replicaCount: 1
  
  # Additional environment variables
  extraEnv: []
    # - name: CUSTOM_VAR
    #   value: "custom-value"
  
  persistence:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClass: ""
    # existingClaim: ""

# App (Frontend) deployment configuration
app:
  image:
    repository: ghcr.io/munenick/refmd-app
    tag: latest
  
  replicaCount: 1
  
  # Additional environment variables
  extraEnv: []
    # - name: CUSTOM_VAR
    #   value: "custom-value"

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    database: refmd
    username: refmd
    password: refmd
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: refmd.local
      paths:
        - path: /
          pathType: Prefix
          service: app
        - path: /api
          pathType: Prefix
          service: api
  tls: []
  #  - secretName: refmd-tls
  #    hosts:
  #      - refmd.local